name: David Stone
favicon: null
layout_spectrum: 0.20699
typography_spectrum: 0.64187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#060606'
    - '#fd7160'
    - '#2c4b4d'
    - '#13a6a6'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
