name: David Stone
favicon: null
layout_spectrum: 0.20699
typography_spectrum: 0.64187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.37422512960620224
  lightness: 0.22909566503949463
  saturation: 0.3656670143827796
  rhythmicContrast: 0.7986888175364584
purpose: []
